name: 'el-toolchain-action'
author: 'TheSnowfield'
branding:
  icon: 'anchor'
  color: 'blue'
description: 'This action provides the command-line compile toolchain for EPL'
inputs:
  file:
    description: 'The name path of the EPL source file (*.e)'
    required: true
  password:
    description: 'Provides the password of the source file'
    required: false
  quiet:
    description: 'Keep compiler quite, only print the error messages'
  compile_opt_fast_array:
    description: 'Enables the fast array accessing mode'
    required: false
  compile_opt_check_stack:
    description: 'Enables the DLL stack error check after calling it'
    required: false
  compile_opt_check_deadloop:
    description: 'Enables the deadloop check'
    required: false
runs:
  using: 'composite'
  steps:
    - id: docker-publish
      run: $GITHUB_ACTION_PATH/entrypoint.sh
      shell: bash
      env:
        INPUT_FILE: ${{ inputs.file }}
        INPUT_PASSWORD: ${{ inputs.password }}
        INPUT_QUIET: ${{ inputs.quiet }}
        INPUT_OPT_FAST_ARRAY: ${{ inputs.compile_opt_fast_array }}
        INPUT_OPT_CHECK_STACK: ${{ inputs.compile_opt_check_stack }}
        INPUT_OPT_CHECK_DEADLOOP: ${{ inputs.compile_opt_check_deadloop }}
