name: Action Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
      - name: Build
        run: |
          ls
          docker build . -t el-toolchain:new

  test-compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
      - uses: ./
        with:
          file: rootfs/test/main.e
          opt_fast_array: true
          opt_stack_check: false
          opt_deadloop_check: false

  release:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    needs:
      - docker-build
      - test-compile
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}
      - name: Publish
        run: |
          git config --global user.email "bot@el-oolchain.action"
          git config --global user.name "Release Bot"
          git tag -fa v1 -m "release v1"
          git push origin v1 --force
